### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-query-builder#108]
My last two builds failed with `Bad credentials` and `Failed to read commit message`

What might this be referring to? @dvargas92495 

```
Run npx samepage build
src built with 0 errors
Preparing to publish zip to destination query-builder as version 1.8.16
Error: Failed to read commit message for de527d8f68585f375c514d9150f240e0689e1d24 in dvargas92495/roamjs-query-builder:
{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
    at /home/runner/work/roamjs-query-builder/roamjs-query-builder/node_modules/@samepage/scripts/build.js:39:46
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async publish (/home/runner/work/roamjs-query-builder/roamjs-query-builder/node_modules/@samepage/scripts/build.js:36:29)
Error: Process completed with exit code 1.
```

**Comment by dvargas92495** [comment]
My github token expired, I'll update
